"""Add game totals fields

Revision ID: add_game_totals
Revises: 
Create Date: 2025-11-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'add_game_totals'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveyresponse', sa.Column('games_1_5_total', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('surveyresponse', sa.Column('games_total', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveyresponse', 'games_total')
    op.drop_column('surveyresponse', 'games_1_5_total')
    # ### end Alembic commands ###